### ISSUE TITLE
Binary mask does not yield desired image/mask

### ISSUE THREAD

**Issue by mitishasurana** [nanoMFG/GSA-Image#78]
![image.png](https://images.zenhubusercontent.com/5e536482f56345cbe04d9cb0/c3e88ce1-1c49-426f-ae30-06151a28dd54)
![image.png](https://images.zenhubusercontent.com/5e536482f56345cbe04d9cb0/3902d59a-44aa-4737-ba56-9a59cae19569)

**Comment by jaschil2** [comment]
Working as intended. Binary mask makes nonzero = 255.
